### ISSUE TITLE
siteflow map

### ISSUE THREAD

**Issue by MarcOverZero** [Mcents/little_shop#13]
Color coded for helpful division of labor.

Admin functionalities noted but not diagrammed.

Some note of possible extensions are included.

[gearupp_siteflow_2.pdf](https://github.com/Mcents/little_shop/files/1174979/gearupp_siteflow_2.pdf)

**Comment by JF-Lalonde** [comment]
Closing this issue, the map is complete. We'll be using the color-coordination to split off and work individually
